### ISSUE TITLE
Build fails since update to Angular 8

### ISSUE THREAD

**Issue by Alex61NN5** [Alex61NN5/angular-universal-pwa-heroku-starter#72]
Getting this error message

```
TypeError: Cannot read property 'properties' of undefined
    at module.exports (/tmp/build_f2de83d063d50f940a16d7a36ce06678/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /tmp/build_f2de83d063d50f940a16d7a36ce06678/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/tmp/build_f2de83d063d50f940a16d7a36ce06678/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-universal-heroku@0.0.0 webpack:server: `webpack --config webpack.server.config.js --progress --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-universal-heroku@0.0.0 webpack:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.pNgEI/_logs/2019-10-10T04_30_23_331Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-universal-heroku@0.0.0 build:ssr: `npm run build:client-and-server-bundles && npm run webpack:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-universal-heroku@0.0.0 build:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.pNgEI/_logs/2019-10-10T04_30_23_346Z-debug.log
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c npm run build:ssr
Directory: /tmp/build_f2de83d063d50f940a16d7a36ce06678
```

Steps to reproduce:

1. Fork this project
2. Follow the steps to deploy to heroku

**Comment by Alex61NN5** [comment]
@hiteshpr Is this something you can look into?

**Comment by manojvignesh** [comment]
Updating webpack-cli to latest seems to fix this issue. Shall i create a PR for this...

**Comment by Alex61NN5** [comment]
@manojvignesh yes please
